// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/shortlink/v1/shortlink.proto

package shortlinkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShortlinkService_CreateShortlink_FullMethodName = "/shortlink.v1.ShortlinkService/CreateShortlink"
)

// ShortlinkServiceClient is the client API for ShortlinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortlinkServiceClient interface {
	CreateShortlink(ctx context.Context, in *CreateShortlinkRequest, opts ...grpc.CallOption) (*CreateShortlinkResponse, error)
}

type shortlinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShortlinkServiceClient(cc grpc.ClientConnInterface) ShortlinkServiceClient {
	return &shortlinkServiceClient{cc}
}

func (c *shortlinkServiceClient) CreateShortlink(ctx context.Context, in *CreateShortlinkRequest, opts ...grpc.CallOption) (*CreateShortlinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShortlinkResponse)
	err := c.cc.Invoke(ctx, ShortlinkService_CreateShortlink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortlinkServiceServer is the server API for ShortlinkService service.
// All implementations must embed UnimplementedShortlinkServiceServer
// for forward compatibility.
type ShortlinkServiceServer interface {
	CreateShortlink(context.Context, *CreateShortlinkRequest) (*CreateShortlinkResponse, error)
	mustEmbedUnimplementedShortlinkServiceServer()
}

// UnimplementedShortlinkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShortlinkServiceServer struct{}

func (UnimplementedShortlinkServiceServer) CreateShortlink(context.Context, *CreateShortlinkRequest) (*CreateShortlinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShortlink not implemented")
}
func (UnimplementedShortlinkServiceServer) mustEmbedUnimplementedShortlinkServiceServer() {}
func (UnimplementedShortlinkServiceServer) testEmbeddedByValue()                          {}

// UnsafeShortlinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortlinkServiceServer will
// result in compilation errors.
type UnsafeShortlinkServiceServer interface {
	mustEmbedUnimplementedShortlinkServiceServer()
}

func RegisterShortlinkServiceServer(s grpc.ServiceRegistrar, srv ShortlinkServiceServer) {
	// If the following call panics, it indicates UnimplementedShortlinkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShortlinkService_ServiceDesc, srv)
}

func _ShortlinkService_CreateShortlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShortlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortlinkServiceServer).CreateShortlink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortlinkService_CreateShortlink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortlinkServiceServer).CreateShortlink(ctx, req.(*CreateShortlinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShortlinkService_ServiceDesc is the grpc.ServiceDesc for ShortlinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortlinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shortlink.v1.ShortlinkService",
	HandlerType: (*ShortlinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShortlink",
			Handler:    _ShortlinkService_CreateShortlink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shortlink/v1/shortlink.proto",
}
