// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/shortlink/v1/shortlink.proto

package shortlinkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortlinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	CustomCode    string                 `protobuf:"bytes,3,opt,name=custom_code,json=customCode,proto3" json:"custom_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortlinkRequest) Reset() {
	*x = CreateShortlinkRequest{}
	mi := &file_proto_shortlink_v1_shortlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortlinkRequest) ProtoMessage() {}

func (x *CreateShortlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_v1_shortlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortlinkRequest.ProtoReflect.Descriptor instead.
func (*CreateShortlinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_v1_shortlink_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortlinkRequest) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *CreateShortlinkRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *CreateShortlinkRequest) GetCustomCode() string {
	if x != nil {
		return x.CustomCode
	}
	return ""
}

type CreateShortlinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	PaymentNo     string                 `protobuf:"bytes,2,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,3,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortlinkResponse) Reset() {
	*x = CreateShortlinkResponse{}
	mi := &file_proto_shortlink_v1_shortlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortlinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortlinkResponse) ProtoMessage() {}

func (x *CreateShortlinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_v1_shortlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortlinkResponse.ProtoReflect.Descriptor instead.
func (*CreateShortlinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_v1_shortlink_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortlinkResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateShortlinkResponse) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *CreateShortlinkResponse) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *CreateShortlinkResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_proto_shortlink_v1_shortlink_proto protoreflect.FileDescriptor

const file_proto_shortlink_v1_shortlink_proto_rawDesc = "" +
	"\n" +
	"\"proto/shortlink/v1/shortlink.proto\x12\fshortlink.v1\"w\n" +
	"\x16CreateShortlinkRequest\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12\x1d\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tR\ttargetUrl\x12\x1f\n" +
	"\vcustom_code\x18\x03 \x01(\tR\n" +
	"customCode\"\x8a\x01\n" +
	"\x17CreateShortlinkResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x02 \x01(\tR\tpaymentNo\x12\x1d\n" +
	"\n" +
	"target_url\x18\x03 \x01(\tR\ttargetUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt2r\n" +
	"\x10ShortlinkService\x12^\n" +
	"\x0fCreateShortlink\x12$.shortlink.v1.CreateShortlinkRequest\x1a%.shortlink.v1.CreateShortlinkResponseBVZTgithub.com/t-kiattisak/event-driven-shortlink-payment/proto/shortlink/v1;shortlinkv1b\x06proto3"

var (
	file_proto_shortlink_v1_shortlink_proto_rawDescOnce sync.Once
	file_proto_shortlink_v1_shortlink_proto_rawDescData []byte
)

func file_proto_shortlink_v1_shortlink_proto_rawDescGZIP() []byte {
	file_proto_shortlink_v1_shortlink_proto_rawDescOnce.Do(func() {
		file_proto_shortlink_v1_shortlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shortlink_v1_shortlink_proto_rawDesc), len(file_proto_shortlink_v1_shortlink_proto_rawDesc)))
	})
	return file_proto_shortlink_v1_shortlink_proto_rawDescData
}

var file_proto_shortlink_v1_shortlink_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_shortlink_v1_shortlink_proto_goTypes = []any{
	(*CreateShortlinkRequest)(nil),  // 0: shortlink.v1.CreateShortlinkRequest
	(*CreateShortlinkResponse)(nil), // 1: shortlink.v1.CreateShortlinkResponse
}
var file_proto_shortlink_v1_shortlink_proto_depIdxs = []int32{
	0, // 0: shortlink.v1.ShortlinkService.CreateShortlink:input_type -> shortlink.v1.CreateShortlinkRequest
	1, // 1: shortlink.v1.ShortlinkService.CreateShortlink:output_type -> shortlink.v1.CreateShortlinkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_shortlink_v1_shortlink_proto_init() }
func file_proto_shortlink_v1_shortlink_proto_init() {
	if File_proto_shortlink_v1_shortlink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortlink_v1_shortlink_proto_rawDesc), len(file_proto_shortlink_v1_shortlink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortlink_v1_shortlink_proto_goTypes,
		DependencyIndexes: file_proto_shortlink_v1_shortlink_proto_depIdxs,
		MessageInfos:      file_proto_shortlink_v1_shortlink_proto_msgTypes,
	}.Build()
	File_proto_shortlink_v1_shortlink_proto = out.File
	file_proto_shortlink_v1_shortlink_proto_goTypes = nil
	file_proto_shortlink_v1_shortlink_proto_depIdxs = nil
}
